server:
  port:
    8080

spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/dbcufarmer?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username:
      root
    password:
      1234
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    initialize:
        true
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 100
        order_inserts: true
#    properties:
#      hibernate:
#        show_sql:
#          true
    database-platform:
      org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto:
        update
      naming:
        implicit-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

        physical-strategy:
          org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl


    show-sql:
      false

  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB

# Cache configuration for Caffeine
#  cache:
#    type:
#      ehcache
#    ehcache:
#      config:
#        classpath:ehcache.xml

logging:
  level:
    root:
      INFO
#    org.hibernate: DEBUG
#    org:
#      springframework:
#        cache:
#          DEBUG
#    org.hibernate.SQL:
#      DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder:
#      TRACE
#    root:
#      DEBUG

    org:
      springframework:
        web:
          DEBUG