server:
  port:
    8080

spring:
  datasource:
    url:
      jdbc:mysql://localhost:3309/dbcufarmer
    username:
      root
    password:
      AlfaTeck@123
    driver-class-name:
      com.mysql.jdbc.Driver
    initialize:
        true
  jpa:
    database-platform:
      org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto:
      update
    show-sql:
      false

  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB

# Cache configuration for Caffeine
  cache:
    cache-names:
      crop
    caffeine:
      spec:
        maximumSize=100

#logging:
#  level:
#    org.hibernate.SQL:
#      DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder:
#      TRACE
#    root:
#      DEBUG

