server:
  port:
    8080

spring:
  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB
  #logging:
  #  level:
  #    root:
  #      DEBUG

simple:
  map:
    {'KEY1': 'value1', 'KEY2': 'value3', 'KEY3': 'value5'}